language: node_js
node_js:
- '9'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
#- ng lint
- ng build --prod
deploy:
  provider: heroku
  api_key:
    secure: uWZgIfqM5clcDQwQmb3+qMviNwblWGnTLZy7eAcjr2So9rCbflYSDH543XvN5/+LptvRmjZ/xxjBW+8PPK9V3Y6UG/akOakGOlhyGZJ0xSmg+K5QTjBkQswBbqHDaU5QM1paxdLINoLNF/rfISHhqUIxLTpKOTj9u1OHgcKS4fP11NzriIj9+psb28tcOCE8APYWpG+fWzd0G5PLZNnsshCznM4x7LouNLD8YrNe6ZnpPVrNs+5c2PHackkEowIPvkjRrwWrJJb/foqHFCeYNPlN2USZCK2Xbsn7CgRPmHq2jDA/z7KqEQfSA0/iG9MxxuPZkXcONUPlEX5WbNgdKPsWFDp7VINTcoWS1SdH19RRRPcGZBHEO2a37g+bGWQqtQXrJnYzVYiEdjPPCQdaSaaWoiVHTrhYy3Eq8Wcpj7gJYpVKEHY6mLZ6Ogv1YFantTfXjkgeb1693uhT5xC0bHIHrEQfXDu7vIYrHIsrsHkdutjVMzDJTM+lv2szByq0XHYjr8c5F32ErvqyPrINh8ROIFtZnNDQy5NF3j/o8w+GJ6MGc7Wa+WzoAEFfhlG2bsg4idU6KbVDGEydLz9/ip4yDvmj14djdgQE46YkZEyQ2bPCz2HFo7MA+mcVmcqZSODsAYpYO+37kWnFqSSmGOtenV+NiKL7CzNv7bxJguI=
  app: lunchsoft-stocks
